@WebAPI_HostAddress = http://localhost:5052

POST {{WebAPI_HostAddress}}/api/problem/addProblem
Accept: application/json
Content-Type: application/json
{
  "name": "Suma și media a două numere folosind funcții",
  "lab": "Laboratorul 2 - Funcții",
  "tags": ["C", "functii", "int", "double"],
  "content": "Se citesc de la tastatură două numere întregi. Să se calculeze suma și media aritmetică folosind funcții separate.",
  "requests": [
    "O funcție pentru sumă",
    "O funcție pentru media aritmetică"
  ],
  "points": 15,
  "inputsJson": [
    "6 4"
  ],
  "ouputsJson": [
    "Suma: 10 Media: 5.00"
  ]
}















###
